version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      - shopping_cart_app
  api-server:
    image: api-server
    ports:
      - "5001:5001"
    networks:
      - shopping_cart_app
    depends_on:
      - mongo
  mongo:
    # image: mongo:3.6.19-xenial
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - shopping_cart_app
    volumes:
      - mongo-data:/data/db
networks: 
  shopping_cart_app:
    driver: bridge
volumes:
  mongo-data:
    driver: local